// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjyyfewyuojjuphnfkxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqeXlmZXd5dW9qanVwaG5ma3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Mjk0NjQsImV4cCI6MjA3MzIwNTQ2NH0.AjnQl-bq0j9PpDv6I57wIY8CXMSDtjF8kX3Gb7Ympeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});